routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
//    return view('welcome');
    return view('auth.login');
});

Auth::routes();
Route::group(['middleware' => ['role:admin|user|super-admin|upazilla-admin']], function () {

    //*  Country Route Section */
    Route::get('country/list', 'CountryController@list')->name('country.list');   // index
    Route::get('country/add', 'CountryController@form')->name('country.form');    // create
    Route::post('country/store', 'CountryController@store')->name('country.store');   // store
    Route::get('country/{id}', 'CountryController@edit')->name('country.edit');   // edit
    Route::post('country/{id}', 'CountryController@update')->name('country.update');    // update
    Route::delete('country/{id}', 'CountryController@destroy')->name('country.delete');    // update

    //*  Division Route Section */
    Route::get('division/list', 'DivisionController@list')->name('division.list');   // index
    Route::get('division/add', 'DivisionController@form')->name('division.form');    // create
    Route::post('division/store', 'DivisionController@store')->name('division.store');   // store
    Route::post('division/divisionSelectAjaxList', 'DivisionController@divisionSelectAjaxList')->name('division.divisionSelectAjaxList');    // Ajax Division List
    Route::get('division/{id}', 'DivisionController@edit')->name('division.edit');   // edit
    Route::post('division/{id}', 'DivisionController@update')->name('division.update');    // update
    Route::delete('division/{id}', 'DivisionController@destroy')->name('division.delete');    // delete

    //*  District Route Section */
    Route::get('district/list', 'DistrictController@list')->name('district.list');   // index
    Route::get('district/add', 'DistrictController@form')->name('district.form');    // create
    Route::post('district/store', 'DistrictController@store')->name('district.store');   // store
    Route::post('district/districtSelectAjaxList', 'DistrictController@districtSelectAjaxList')->name('district.districtSelectAjaxList');    // Ajax District List
    Route::get('district/{id}', 'DistrictController@edit')->name('district.edit');   // edit
    Route::post('district/{id}', 'DistrictController@update')->name('district.update');    // update
    Route::delete('district/{id}', 'DistrictController@destroy')->name('district.delete');    // delete

    //*  Upazila-- Route Section */
    Route::get('upazila/list', 'UpazilaController@list')->name('upazila.list');   // index
    Route::get('upazila/add', 'UpazilaController@form')->name('upazila.form');    // create
    Route::post('upazila/store', 'UpazilaController@store')->name('upazila.store');   // store
    Route::post('upazila/upazilaSelectAjaxList', 'UpazilaController@upazilaSelectAjaxList')->name('upazila.upazilaSelectAjaxList');    // Ajax Upazila List
    Route::get('upazila/{id}', 'UpazilaController@edit')->name('upazila.edit');   // edit
    Route::post('upazila/{id}', 'UpazilaController@update')->name('upazila.update');    // update
    Route::delete('upazila/{id}', 'UpazilaController@destroy')->name('upazila.delete');    // delete

    //*  Union Route Section */
    Route::get('union/list', 'UnionController@list')->name('union.list');   // index
    Route::get('union/add', 'UnionController@form')->name('union.form');    // create
    Route::post('union/store', 'UnionController@Store')->name('union.store');   // store
    Route::post('union/unionSelectAjaxList', 'UnionController@unionSelectAjaxList')->name('union.unionSelectAjaxList');    // Ajax District List
    Route::get('union/{id}', 'UnionController@edit')->name('union.edit');   // edit
    Route::post('union/{id}', 'UnionController@update')->name('union.update');    // update
    Route::delete('union/{id}', 'UnionController@destroy')->name('union.delete');    // delete

    Route::get('/home', 'HomeController@index')->name('dashboard');

//    Route::get('/roles', 'PermissionController@Permission');

//    Route::get('/admin', function () {
//        return 'Welcome Admin';
//    });

//    bondobosto route
//    Route::get('/applicant', 'ApplicanrController@index')->name('applicant.list');

//    Land Route
    Route::post('/lands/getLandInfoById', 'LandController@getLandInfoById')->name('lands.getLandInfoById');
    Route::resource('/lands', 'LandController');

//    Applicant Route
    Route::resource('/applicants', 'ApplicantController');

//    Land Assign Route
    Route::resource('/assign_lands', 'AssignLandController');

//    Role Routs
    Route::Resource('/roles', 'RoleController');
    Route::get('/role-setting', 'RoleController@roleSetting')->name('roles.roleSetting');
    Route::post('/role-setting','RoleController@roleSetting')->name('roles.roleSetting');
    Route::post('/update-role-setting','RoleController@updateRoleSetting')->name('roles.updateRoleSetting');

//    Permission Routs
    Route::resource('/permissions','PermissionController');

//    User Route
//    Route::get("/users/datatable", 'UserController@datatable')->name("users.datatable"); // for Data Table Export
//    Route::get("/users/datatable/getData", 'UserController@getData')->name("users.getData"); // for datatable Export
    Route::get("/users/export", 'UserController@export')->name("users.export"); // for datatable Export
    Route::Resource('/users', 'UserController');
    Route::get("/change-password", 'UserController@changepass')->name("users.changepass"); // for pass change
    Route::post("/change-password", 'UserController@changepass')->name("users.changepass"); // for pass change
    Route::post("/reset-password", 'UserController@resetpass')->name("users.resetpass"); // for pass reset

//    Cache Clear Route
    Route::get('/clear-cache', function() {
        Artisan::call('cache:clear');
        Artisan::call('view:clear');
        Artisan::call('config:cache');
        return "Cache cleared";
    });
});


//Route::group(['middleware' => ['role:developer|manager|superadmin']], function () {
//});

/*
Verb            URI                         Action          Route Name
GET             /photos                     index           photos.index
GET             /photos/create              create          photos.create
POST            /photos                     store           photos.store
GET             /photos/{photo}             show            photos.show
GET             /photos/{photo}/edit        edit            photos.edit
PUT/PATCH       /photos/{photo}             update          photos.update
DELETE          /photos/{photo}             destroy         photos.destroy
*/

app/Models/AssignLand.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class AssignLand extends Model
{
    protected $fillable = [
        'created_by', 'updated_by', 'status', 'is_active'
    ];

    public function saveData($data)
    {
        foreach ($data->request as $key => $value) {
            if ($key != "_token") {
                $this->$key = $value;
            }
        }
        $this->created_by = auth()->user()->id;
        $this->status = config('constants.landStatus.Unassigned');
        $this->is_active = config('constants.status.Active');
        $this->from = date("Y");
        $this->to = date("Y") + 1;
//        $dob = $data->dob;
//        $this->dob = date('Y-m-d', strtotime($data->dob));

//        pr($dob);
//        dd($this);
        $this->save();
        return $this->id;
    }

    public function updateData($data)
    {
//        dd($data['id']);
        $ticket = $this->find($data['id']);
        foreach ($data->request as $key => $value) {
            if ($key != "_token" && $key != "_method") {
                $ticket->$key = $value;
            }
        }
        $ticket->updated_by = auth()->user()->id;
//        $ticket->dob = date('Y-m-d', strtotime($ticket->dob));
        $ticket->save();
        return 1;
    }

    public function lands()
    {
        return $this->hasMany('App\Models\Lands')->orderBy('land_id', 'ASC');
    }
}

app/Http/Controllers/AssignLandController.php
<?php

namespace App\Http\Controllers;

use App\Models\AssignLand;
use App\Models\Applicant;
use App\Models\District;
use App\Models\Land;
use App\Models\Union;
use App\Models\Upazila;
use Illuminate\Http\Request;
use DataTables;
use Illuminate\Support\Facades\DB;
use Auth;

class AssignLandController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $page_title = 'বন্দবস্ত বন্টন তালিকা';
        $data = AssignLand::latest('assign_lands.created_at')->where('assign_lands.is_active','!=',config('constants.status.Deleted'))
            ->select("assign_lands.id", "assign_lands.clients", "assign_lands.from", "assign_lands.to", "assign_lands.status", "lands.dist", "lands.upa", "lands.mouja", "lands.khotiyan", "lands.dag_no", "lands.lnd_size", "lands.lnd_price", "lands.case_no" )
            ->leftJoin('lands', 'assign_lands.land_id', 'lands.id')
            ->get();

        if ($request->ajax()) {
            $districtListArr = District::pluck('bn_name', 'id');
            $upazillaListArr = Upazila::pluck('bn_name', 'id');
            $unionListArr = Union::pluck('bn_name', 'id');
            return DataTables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function ($row) {
                    $action = '<a class="btn btn-success" id="edit-user" href= ' . route('assign_lands.edit', $row->id) . '>Edit </a>
<meta name="csrf-token" content="{{ csrf_token() }}">
<a id=' . $row->id . ' href=' . route('assign_lands.destroy', $row->id) . ' class="btn btn-danger delete-user">Delete</a>';
                    return $action;
                })
                ->addColumn('names', function ($row) {
                    $clientsArr = getClientInfoByIds($row->clients);

                    $str = "";
                    foreach ($clientsArr as $keys => $values){
                        $str .= $values->name.'('.$values->nid.'), <br/>';
                    }
                    return $str;
                })
                ->rawColumns(['action','names'])
                ->editColumn('union', function ($row) use($unionListArr) {
                    $union = "";
                    if($row->union >= 1){
                        $union = $unionListArr[$row->union];
                    }else{
                        $union = 'পৌরসভা';
                    }
                    return $union;
                })
                ->editColumn('dist', function ($row) use($districtListArr) {
                    return $districtListArr[$row->dist];
                })
                ->editColumn('upa', function ($row) use($upazillaListArr) {
                    return $upazillaListArr[$row->upa];
                })
                ->make(true);
//            <a class="btn btn-info" id="show-user" href=' . route('lands.show', $row->id) . '>Show</a>
        }

        return view('assign_lands.index', compact('page_title'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $page_title = 'বন্দবস্ত বন্টন ফর্ম';
        $landList = Land::pluck('case_no', 'id');
        $cilentList = Applicant::select('id', DB::raw("CONCAT(name,' (',nid,') ') AS full_name"))
            ->where('is_active',"!=",config('constants.status.Deleted'))
            ->where('status',"=",config('constants.landStatus.Unassigned'))
            ->get()
            ->pluck('full_name', 'id');
        $districtListArr = District::pluck('bn_name', 'id');
        $upozillaListArr = Upazila::pluck('bn_name', 'id');
        return view('assign_lands.create', compact('districtListArr', 'upozillaListArr', 'page_title', 'cilentList','landList'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $assignLandModel = new AssignLand();

        DB::beginTransaction();
        try{
            $formData = $request->all();
            $clientList = '';
            $clientArr = $formData['clients'];
            foreach ($clientArr as $key => $vals){
                $clientList = $vals .','.$clientList;
            }
            $clientList = rtrim($clientList, ", ");
            $request->request->add(['clients' => $clientList]);
            $resData = $assignLandModel->saveData($request);

            DB::commit();
            return redirect('/assign_lands')->with('success', 'Assigned successfully');
        }catch (\Exception $exception){
            DB::rollback();
            return redirect('/assign_lands/create')->with('error', $exception->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\AssignLand  $assignLand
     * @return \Illuminate\Http\Response
     */
    public function show(AssignLand $assignLand)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\AssignLand  $assignLand
     * @return \Illuminate\Http\Response
     */
    public function edit(AssignLand $assignLand)
    {
        $page_title = 'বন্দবস্ত বন্টন তথ্য সংশোধন ফর্ম';
        try {
//            $assignLandData = $assignLandModel->where('assign_lands.id', $id)->firstOrFail();
            $assignLand->clients = explode(',',$assignLand->clients);
            $id = $assignLand->id;

            $landArr = Land::pluck('case_no', 'id');
            $landDataArr = Land::where('id','=',$assignLand->land_id)->get()->toArray();
            $landDataArr = $landDataArr[0];
            $cilentList = Applicant::select('id', DB::raw("CONCAT(name,' (',nid,') ') AS full_name"))
                ->where('is_active',"!=",config('constants.status.Deleted'))
                ->where('status',"=",config('constants.landStatus.Unassigned'))
                ->get()
                ->pluck('full_name', 'id');
            return view('assign_lands.edit', compact( 'page_title','assignLand', 'id','landArr','landDataArr','cilentList'));
        } catch (\Exception $exception) {
            dd($exception);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\AssignLand  $assignLand
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $assignLandModel = new AssignLand();

        DB::beginTransaction();
        try{
            $formData = $request->all();
            $clientList = '';
            $clientArr = $formData['clients'];
            foreach ($clientArr as $key => $vals){
                $clientList = $vals .','.$clientList;
            }
            $clientList = rtrim($clientList, ", ");
            $request->request->add(['clients' => $clientList]);
            $request->request->add(['id' => $id]);
            $resData = $assignLandModel->updateData($request);

            DB::commit();
            return redirect('/assign_lands')->with('success', 'Assigned successfully');
        }catch (\Exception $exception){
            DB::rollback();
            return redirect("/assign_lands/{$id}/edit")->with('error', $exception->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\AssignLand  $assignLand
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, AssignLand $assignLand)
    {
        $assignLandModel = new AssignLand();

        DB::beginTransaction();
        try {
            if (!empty($assignLand->id)) {
                $updateData = [
                    'is_active' => config('constants.status.Deleted'),
                ];

                $assignLandModel->where('id', '=', $assignLand->id)->update($updateData);
                DB::commit();
                $request->session()->flash('success', 'তথ্য সফলভাবে নুছে ফেলা হয়েছে...');
                return response()->json(['status' => 'success']);
            } else {
                DB::rollback();
                $request->session()->flash('errors', 'কোন তথ্য পাওয়া জায় নি...');
                return response()->json(['status' => 'error']);
            }
        } catch (\Exception $exception) {
            DB::rollback();
            $request->session()->flash('errors', 'তথ্য সফলভাবে মুছা সম্ভব হয় নি...');
            return response()->json(['status' => 'error']);
        }
    }
}

resources/views/assign_lands/create.blade.php
@extends('layouts.app')

@section('pagetitle')
    <h1 class="m-0">{{ $page_title }}</h1>
@endsection

@section('breadcrumb')
    <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="#">Home</a></li>
        <li class="breadcrumb-item active">Starter Page</li>
    </ol>
@endsection

@section('content')
    <form class="form-horizontal" role="form" action="{{ route('assign_lands.store') }}" method="POST"
          enctype="multipart/form-data" id="reg_form">
        {{ csrf_field() }}

        <input type="hidden" id="case_no" name="case_no" value="">

        <div class="card  card-primary">
            <div class="card-header">
                <h3 class="card-title">জমি বাছাই</h3>

                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    {{--                <button type="button" class="btn btn-tool" data-card-widget="remove">--}}
                    {{--                    <i class="fas fa-times"></i>--}}
                    {{--                </button>--}}
                </div>
            </div>
            <!-- /.card-header -->
            <!-- /.card-header -->
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>জমি বাছাই <span class="reqrd"> *</span></label>
                            <select class="form-control select2bs4" id="land_id" name="land_id" required>
                                <option value="">--- বাছাই করুণ ---</option>
                                <?php
                                foreach ($landList as $id => $name){ ?>
                                <option value="{{ $id }}">{{ $name }}</option>
                                <?php }
                                ?>
                            </select>
                            <span class="help-inline col-xs-12 col-sm-7">
                            @if ($errors->has('land_id'))
                                    <span class="help-block middle">
                                    <strong>{{ $errors->first('land_id') }}</strong>
                                </span>
                                @endif
                        </span>
                        </div>
                        <!-- /.form-group -->
                    </div>
                    <!-- /.col -->
                    <div class="col-md-6">
                        <div class="form-group land_info">
                            <table id="land_info" class="table table-bordered data-table">
                                <thead>
                                <th>কেস নং</th>
                                <th>জেলা</th>
                                <th>উপজেলা জেলা</th>
                                <th>মৌজা</th>
                                <th>খতিয়ান</th>
                                <th>দাগ নং</th>
                                <th>জমির পরিমাণ</th>
                                <th>জমির মূল্য</th>
                                </thead>
                                <tbody>
                                <tr>
                                    <td id="td_case"></td>
                                    <td id="td_dist"></td>
                                    <td id="td_upa"></td>
                                    <td id="td_mouja"></td>
                                    <td id="td_khotiyan"></td>
                                    <td id="td_dag_no"></td>
                                    <td id="td_size"></td>
                                    <td id="td_price"></td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                        <!-- /.form-group -->
                    </div>
                    <!-- /.col -->
                </div>
            </div>
        </div>

        <div class="card  card-primary">
            <div class="card-header">
                <h3 class="card-title">বন্দবস্থ বাছাই</h3>

                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    {{--                <button type="button" class="btn btn-tool" data-card-widget="remove">--}}
                    {{--                    <i class="fas fa-times"></i>--}}
                    {{--                </button>--}}
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>গ্রহণকারী বাছাই করুণ</label>
                            <select class="select2bs4" multiple="multiple" data-placeholder="Select a State"
                                    style="width: 100%;" name="clients[]" id="clients">
                                <?php
                                foreach ($cilentList as $id => $name){ ?>
                                <option value="{{ $id }}">{{ $name }}</option>
                                <?php }
                                ?>
                            </select>
                            <span class="help-inline col-xs-12 col-sm-7">
                            @if ($errors->has('clients'))
                                    <span class="help-block middle">
                                    <strong>{{ $errors->first('clients') }}</strong>
                                </span>
                                @endif
                        </span>
                        </div>
                        <!-- /.form-group -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.card-body -->

            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>
@endsection

@section('custom_script')
    <script type="text/javascript">
        $(document).ready(function () {
            //Initialize Select2 Elements
            $('.select2').select2();

            //Initialize Select2 Elements
            $('.select2bs4').select2({
                theme: 'bootstrap4'
            })

            //Datemask dd/mm/yyyy
            $('#datemask').inputmask('mm/dd/yyyy', {'placeholder': 'mm/dd/yyyy'})
            //Money Euro
            $('[data-mask]').inputmask()
        });

        $('#dist').on('change', function () {
            var districtID = $(this).val();
            var token = $("input[name='_token']").val();
            var url = "{{ route('upazila.upazilaSelectAjaxList') }}";
            if (districtID) {
                $('select[name="upa"]').empty();
                upazillaList(districtID, token, url);
            } else {
                $('select[name="upa"]').empty();
            }
        });

        $('#upa').on('change', function () {
            var upazilaID = $(this).val();
            var token = $("input[name='_token']").val();
            var url = "{{ route('union.unionSelectAjaxList') }}";
            if (upazilaID) {
                $('select[name="union"]').empty();
                unionList(upazilaID, token, url);
            }
        });

        $('#lnd_cat').on('change', function () {
            var sizeVal = $('#lnd_size').val();
            var catVal = $(this).val();
            if (sizeVal != null && sizeVal != '') {
                var calculation = (parseInt(catVal) * parseInt(sizeVal));
                $('#lnd_price').val(calculation);
            }

        });

        $('#lnd_size').on('change', function () {
            var catVal = $('#lnd_cat').val();
            var sizeVal = $(this).val();
            if (catVal != null && catVal != '') {
                var calculation = (parseInt(catVal) * parseInt(sizeVal));
                $('#lnd_price').val(calculation);
            }
        });

        $('#land_id').on('change', function () {
            var landId = $(this).val();
            var token = $("input[name='_token']").val();
            var url = "{{ route('lands.getLandInfoById') }}";
            {{--var value = "<?php getLandById(landId); ?>";--}}
            $.ajax({
                url: url,
                method: 'POST',
                data: {landId: landId, _token: token},
                dataType: "json",
                success: function (data) {
                    // console.log(data);
                    // $('select[name="upa"]').append('<option value="">' + "--- বাছাই করুন ---" + '</option>');
                    $.each(data, function (keys, values) {
                        // console.log(values.dag_no);
                        $("#td_case").html(values.case_no);
                        $("#td_dist").html(values.dist);
                        $("#td_upa").html(values.upa);
                        $("#td_mouja").html(values.mouja);
                        $("#td_khotiyan").html(values.khotiyan);
                        $("#td_dag_no").html(values.dag_no);
                        $("#td_size").html(values.lnd_size);
                        $("#td_price").html(values.lnd_price);
                        $('#case_no').val(values.case_no)
                    });
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    alert("Status: " + textStatus);
                    alert("Error: " + errorThrown);
                    console.log(XMLHttpRequest);
                    console.log(textStatus);
                    console.log(errorThrown);
                }
            });
        });

        function upazillaList(districtID, token, url) {
            $.ajax({
                url: url,
                method: 'POST',
                data: {districtID: districtID, _token: token},
                dataType: "json",
                success: function (data) {
                    console.log(data);
                    $('select[name="upa"]').append('<option value="">' + "--- বাছাই করুন ---" + '</option>');
                    $.each(data, function (key, value) {
                        $('select[name="upa"]').append('<option value="' + key + '">' + value + '</option>');
                    });
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    alert("Status: " + textStatus);
                    alert("Error: " + errorThrown);
                    console.log(XMLHttpRequest);
                    console.log(textStatus);
                    console.log(errorThrown);
                }
            });
        };

        function unionList(upazilaID, token, url) {
            $.ajax({
                url: url,
                method: 'POST',
                data: {upazilaID: upazilaID, _token: token},
                dataType: "json",
                success: function (data) {
                    console.log(data);
                    $('select[name="union"]').append('<option value="">' + "--- বাছাই করুন ---" + '</option>');
                    $('select[name="union"]').append('<option value="' + 0 + '">' + "পৌরসভা" + '</option>');

                    $.each(data, function (key, value) {
                        $('select[name="union"]').append('<option value="' + key + '">' + value + '</option>');
                    });
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    alert("Status: " + textStatus);
                    alert("Error: " + errorThrown);
                    console.log(XMLHttpRequest);
                    console.log(textStatus);
                    console.log(errorThrown);
                }
            });
        };

    </script>
@endsection