routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
//    return view('welcome');
    return view('auth.login');
});

Auth::routes();
Route::group(['middleware' => ['role:admin|user|super-admin|upazilla-admin']], function () {

    //*  Country Route Section */
    Route::get('country/list', 'CountryController@list')->name('country.list');   // index
    Route::get('country/add', 'CountryController@form')->name('country.form');    // create
    Route::post('country/store', 'CountryController@store')->name('country.store');   // store
    Route::get('country/{id}', 'CountryController@edit')->name('country.edit');   // edit
    Route::post('country/{id}', 'CountryController@update')->name('country.update');    // update
    Route::delete('country/{id}', 'CountryController@destroy')->name('country.delete');    // update

    //*  Division Route Section */
    Route::get('division/list', 'DivisionController@list')->name('division.list');   // index
    Route::get('division/add', 'DivisionController@form')->name('division.form');    // create
    Route::post('division/store', 'DivisionController@store')->name('division.store');   // store
    Route::post('division/divisionSelectAjaxList', 'DivisionController@divisionSelectAjaxList')->name('division.divisionSelectAjaxList');    // Ajax Division List
    Route::get('division/{id}', 'DivisionController@edit')->name('division.edit');   // edit
    Route::post('division/{id}', 'DivisionController@update')->name('division.update');    // update
    Route::delete('division/{id}', 'DivisionController@destroy')->name('division.delete');    // delete

    //*  District Route Section */
    Route::get('district/list', 'DistrictController@list')->name('district.list');   // index
    Route::get('district/add', 'DistrictController@form')->name('district.form');    // create
    Route::post('district/store', 'DistrictController@store')->name('district.store');   // store
    Route::post('district/districtSelectAjaxList', 'DistrictController@districtSelectAjaxList')->name('district.districtSelectAjaxList');    // Ajax District List
    Route::get('district/{id}', 'DistrictController@edit')->name('district.edit');   // edit
    Route::post('district/{id}', 'DistrictController@update')->name('district.update');    // update
    Route::delete('district/{id}', 'DistrictController@destroy')->name('district.delete');    // delete

    //*  Upazila-- Route Section */
    Route::get('upazila/list', 'UpazilaController@list')->name('upazila.list');   // index
    Route::get('upazila/add', 'UpazilaController@form')->name('upazila.form');    // create
    Route::post('upazila/store', 'UpazilaController@store')->name('upazila.store');   // store
    Route::post('upazila/upazilaSelectAjaxList', 'UpazilaController@upazilaSelectAjaxList')->name('upazila.upazilaSelectAjaxList');    // Ajax Upazila List
    Route::get('upazila/{id}', 'UpazilaController@edit')->name('upazila.edit');   // edit
    Route::post('upazila/{id}', 'UpazilaController@update')->name('upazila.update');    // update
    Route::delete('upazila/{id}', 'UpazilaController@destroy')->name('upazila.delete');    // delete

    //*  Union Route Section */
    Route::get('union/list', 'UnionController@list')->name('union.list');   // index
    Route::get('union/add', 'UnionController@form')->name('union.form');    // create
    Route::post('union/store', 'UnionController@Store')->name('union.store');   // store
    Route::post('union/unionSelectAjaxList', 'UnionController@unionSelectAjaxList')->name('union.unionSelectAjaxList');    // Ajax District List
    Route::get('union/{id}', 'UnionController@edit')->name('union.edit');   // edit
    Route::post('union/{id}', 'UnionController@update')->name('union.update');    // update
    Route::delete('union/{id}', 'UnionController@destroy')->name('union.delete');    // delete

    Route::get('/home', 'HomeController@index')->name('dashboard');

//    Route::get('/roles', 'PermissionController@Permission');

//    Route::get('/admin', function () {
//        return 'Welcome Admin';
//    });

//    bondobosto route
//    Route::get('/applicant', 'ApplicanrController@index')->name('applicant.list');

//    Land Route
    Route::post('/lands/getLandInfoById', 'LandController@getLandInfoById')->name('lands.getLandInfoById');
    Route::resource('/lands', 'LandController');

//    Applicant Route
    Route::resource('/applicants', 'ApplicantController');

//    Land Assign Route
    Route::resource('/assign_lands', 'AssignLandController');

//    Role Routs
    Route::Resource('/roles', 'RoleController');
    Route::get('/role-setting', 'RoleController@roleSetting')->name('roles.roleSetting');
    Route::post('/role-setting','RoleController@roleSetting')->name('roles.roleSetting');
    Route::post('/update-role-setting','RoleController@updateRoleSetting')->name('roles.updateRoleSetting');

//    Permission Routs
    Route::resource('/permissions','PermissionController');

//    User Route
//    Route::get("/users/datatable", 'UserController@datatable')->name("users.datatable"); // for Data Table Export
//    Route::get("/users/datatable/getData", 'UserController@getData')->name("users.getData"); // for datatable Export
    Route::get("/users/export", 'UserController@export')->name("users.export"); // for datatable Export
    Route::Resource('/users', 'UserController');
    Route::get("/change-password", 'UserController@changepass')->name("users.changepass"); // for pass change
    Route::post("/change-password", 'UserController@changepass')->name("users.changepass"); // for pass change
    Route::post("/reset-password", 'UserController@resetpass')->name("users.resetpass"); // for pass reset

//    Cache Clear Route
    Route::get('/clear-cache', function() {
        Artisan::call('cache:clear');
        Artisan::call('view:clear');
        Artisan::call('config:cache');
        return "Cache cleared";
    });
});


//Route::group(['middleware' => ['role:developer|manager|superadmin']], function () {
//});

/*
Verb            URI                         Action          Route Name
GET             /photos                     index           photos.index
GET             /photos/create              create          photos.create
POST            /photos                     store           photos.store
GET             /photos/{photo}             show            photos.show
GET             /photos/{photo}/edit        edit            photos.edit
PUT/PATCH       /photos/{photo}             update          photos.update
DELETE          /photos/{photo}             destroy         photos.destroy
*/

app/Permission.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Permission extends Model
{
    public function roles() {

        return $this->belongsToMany(Role::class,'roles_permissions');
            
     }
     
     public function users() {
     
        return $this->belongsToMany(User::class,'users_permissions');
            
     }
}

app/Http/Controllers/PermissionController.php
<?php
namespace App\Http\Controllers;

use App\Permission;
use App\Role;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use DataTables;

class PermissionController extends Controller
{
    public function index(Request $request){
        $page_title = 'সকল অনুমতির তালিকা';
        $data = Permission::orderby('id','asc')->get();
        $controller_list = config('constants.controller_list.list');
//        dd($controller_list);
        if ($request->ajax()) {
            return DataTables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function ($row) {
                    $action = '<a class="btn btn-success" id="edit-permission" href= ' . route('permissions.edit', $row->id) . '>Edit </a>
<meta name="csrf-token" content="{{ csrf_token() }}">
<a id=' . $row->id . ' href=' . route('permissions.destroy', $row->id) . ' class="btn btn-danger delete-permission">Delete</a>';
                    return $action;
                })
                ->editColumn('controller', function ($row) use($controller_list) {
                    return $controller_list[$row->controller];
                })
                ->rawColumns(['action'])
                ->make(true);
//            <a class="btn btn-info" id="show-user" href=' . route('lands.show', $row->id) . '>Show</a>
        }

        return view('permissions.index', compact('page_title'));
    }

    public function create()
    {
        $page_title = 'অনুমতি তৈরী';
        return view('permissions.create', compact('page_title'));
    }

    public function store(Request $request)
    {
        $formData = $request->all();

        DB::beginTransaction();
        try {
            $permissionName = $formData['name'];
            $controller = $formData['controller'];
            $slug = Str::slug($permissionName);
            $request->request->add(['slug' => $slug]);

            $data = $this->validate($request, [
                'name' => 'required',
                'controller' => 'required',
            ], [
                'name.required' => 'অনুগ্রহ করে অনুমতি প্রদাল করুন',
                'controller.required' => 'অনুগ্রহ করে সেকশন প্রদাল করুন',
            ]);

            $permissionModel = new Permission();
            $permissionModel->slug = $slug;
            $permissionModel->name = $permissionName;
            $permissionModel->controller = $controller;
            $permissionModel->save();

//            $lastInsertedId = $landModel->saveData($request);

            DB::commit();
            return redirect('/permissions')->with('success', 'নতুন অনুমতি যুক্ত হয়েছে।');
        } catch (\Exception $exception) {
            DB::rollback();
            return redirect('/permissions/create')->with('error', $exception->getMessage());
//			$request->session()->flash('errors', $exception->getMessage());
            //$request->session()->flash('errors', $exception);
        }
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $page_title = 'অনুমতি সংশোধন';
//        $countryData = Country::all();
        $permissionModel = new Permission();
        try {
            $permissionData = $permissionModel->where('permissions.id', $id)
                ->firstOrFail();

            return view('permissions.edit', compact('page_title', 'permissionData', 'id'));
        } catch (\Exception $exception) {
        }
    }

    public function update(Request $request, $id)
    {
        $formData = $request->all();
        DB::beginTransaction();
        try {
            $request->request->add(['id' => $id]);
            $data = $this->validate($request, [
                'name' => 'required',
                'controller' => 'required',
            ], [
                'name.required' => 'অনুগ্রহ করে অনুমতি প্রদাল করুন',
                'controller.required' => 'অনুগ্রহ করে সেকশন প্রদাল করুন',
            ]);

            $permissionName = $formData['name'];
            $controller = $formData['controller'];

            $data = Permission::find($id);
            $data->name = $permissionName;
            $data->controller = $controller;

            $data->save();
//            dd($request);
            DB::commit();

//            return redirect()->back()->with('success', 'data updated');
            return redirect('/permissions')->with('success', 'তথ্য সফলভাবে সংশোধন হয়েছে।');
        } catch (\Exception $exception) {
            DB::rollback();
            dd($exception);
            return redirect("/permissions/$id/edit")->with('error', 'তথ্য সংশোধন সম্ভব হয় নি। ' . $exception->getMessage());
//			$request->session()->flash('errors', $exception->getMessage());
            //$request->session()->flash('errors', $exception);
        }
    }

    public function destroy(Request $request, $id)
    {
        DB::beginTransaction();
        try {
            if (!empty($id)) {
                Permission::destroy($id);
                DB::commit();
                $request->session()->flash('success', 'তথ্য সফলভাবে নুছে ফেলা হয়েছে...');
                return response()->json(['status' => 'success']);
            } else {
                DB::rollback();
                $request->session()->flash('errors', 'কোন তথ্য পাওয়া জায় নি...');
                return response()->json(['status' => 'error']);
            }
        } catch (\Exception $exception) {
            DB::rollback();
            $request->session()->flash('errors', 'তথ্য সফলভাবে মুছা সম্ভব হয় নি...');
            return response()->json(['status' => 'error']);
        }
    }

    public function Permission()
    {
    	$dev_permission = Permission::where('slug','create-tasks')->first();
		$manager_permission = Permission::where('slug', 'edit-users')->first();

		//RoleTableSeeder.php
		$dev_role = new Role();
		$dev_role->slug = 'developer';
		$dev_role->name = 'Front-end Developer';
		$dev_role->save();
		$dev_role->permissions()->attach($dev_permission);

		$manager_role = new Role();
		$manager_role->slug = 'manager';
		$manager_role->name = 'Assistant Manager';
		$manager_role->save();
		$manager_role->permissions()->attach($manager_permission);

		$dev_role = Role::where('slug','developer')->first();
		$manager_role = Role::where('slug', 'manager')->first();

		$createTasks = new Permission();
		$createTasks->slug = 'create-tasks';
		$createTasks->name = 'Create Tasks';
		$createTasks->save();
		$createTasks->roles()->attach($dev_role);

		$editUsers = new Permission();
		$editUsers->slug = 'edit-users';
		$editUsers->name = 'Edit Users';
		$editUsers->save();
		$editUsers->roles()->attach($manager_role);

		$dev_role = Role::where('slug','developer')->first();
		$manager_role = Role::where('slug', 'manager')->first();
		$dev_perm = Permission::where('slug','create-tasks')->first();
		$manager_perm = Permission::where('slug','edit-users')->first();

		$developer = new User();
		$developer->name = 'Mahedi Hasan';
		$developer->email = 'mahedi@gmail.com';
		$developer->password = bcrypt('secrettt');
		$developer->save();
		$developer->roles()->attach($dev_role);
		$developer->permissions()->attach($dev_perm);

		$manager = new User();
		$manager->name = 'Hafizul Islam';
		$manager->email = 'hafiz@gmail.com';
		$manager->password = bcrypt('secrettt');
		$manager->save();
		$manager->roles()->attach($manager_role);
		$manager->permissions()->attach($manager_perm);


		return redirect()->back();
    }
}

resources/views/permissions/create.blade.php
@extends('layouts.app')

@section('pagetitle')
    <h1 class="m-0">{{ $page_title }}</h1>
@endsection

@section('breadcrumb')
    <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="#">Home</a></li>
        <li class="breadcrumb-item active">Starter Page</li>
    </ol>
@endsection

@section('content')
    <form class="form-horizontal" role="form" action="{{ route('permissions.store') }}" method="POST"
          enctype="multipart/form-data" id="reg_form">
        {{ csrf_field() }}


        <div class="card  card-primary">
            <div class="card-header">
                <h3 class="card-title">নতুন অনুমতি</h3>

                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    {{--                <button type="button" class="btn btn-tool" data-card-widget="remove">--}}
                    {{--                    <i class="fas fa-times"></i>--}}
                    {{--                </button>--}}
                </div>
            </div>
            <!-- /.card-header -->
            <!-- /.card-body -->
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>অনুমতির নাম<span class="reqrd"> *</span></label>
                            <input type="text" id="name" name="name" class="form-control" placeholder="অনুমতির নাম"
                                   required>
                            <span class="help-inline col-xs-12 col-sm-7">
                            @if ($errors->has('name'))
                                    <span class="help-block middle">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                                @endif
                        </span>
                        </div>
                        <!-- /.form-group -->
                        <div class="form-group">
                            <label>সেকশন <span class="reqrd"> *</span></label>
                            <select class="form-control select2bs4" id="controller" name="controller" required>
                                <option value="">--- বাছাই করুণ ---</option>
                                <?php
                                $controller = config('constants.controller_list.list');
                                foreach ($controller as $id => $name){ ?>
                                <option value="{{ $id }}">{{ $name }}</option>
                                <?php }
                                ?>
                            </select>

                            <span class="help-inline col-xs-12 col-sm-7">
                            @if ($errors->has('controller'))
                                    <span class="help-block middle">
                                    <strong>{{ $errors->first('controller') }}</strong>
                                </span>
                                @endif
                        </span>
                        </div>
                        <!-- /.form-group -->
                    {{--                    <div class="form-group">--}}
                    {{--                        <label>খতিয়ান</label>--}}
                    {{--                        <input type="text" class="form-control" placeholder="Enter ...">--}}
                    {{--                    </div>--}}
                    <!-- /.form-group -->
                    </div>
                    <!-- /.col -->
                </div>
            </div>
            <!-- /.card-footer -->
            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>
@endsection

@section('custom_script')
    <script type="text/javascript">
        $(document).ready(function () {
        });
    </script>
@endsection

resources/views/permissions/edit.blade.php
@extends('layouts.app')

@section('pagetitle')
    <h1 class="m-0">{{ $page_title }}</h1>
@endsection

@section('breadcrumb')
    <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="#">Home</a></li>
        <li class="breadcrumb-item active">Starter Page</li>
    </ol>
@endsection

@section('content')
    <form class="form-horizontal" role="form" action="{{ route('permissions.update', $id) }}" method="POST"
          enctype="multipart/form-data" id="reg_form">
        <input type="hidden" name="_method" value="PUT">
        {{ csrf_field() }}


        <div class="card  card-primary">
            <div class="card-header">
                <h3 class="card-title">নতুন অনুমতি</h3>

                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    {{--                <button type="button" class="btn btn-tool" data-card-widget="remove">--}}
                    {{--                    <i class="fas fa-times"></i>--}}
                    {{--                </button>--}}
                </div>
            </div>
            <!-- /.card-header -->
            <!-- /.card-body -->
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>অনুমতির নামঃ<span class="reqrd"> *</span></label>
                            <input type="text" id="name" name="name" class="form-control" placeholder="অনুমতির নাম"
                                   required value="{{ $permissionData->name }}">
                            <span class="help-inline col-xs-12 col-sm-7">
                            @if ($errors->has('name'))
                                    <span class="help-block middle">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                                @endif
                        </span>
                        </div>
                        <!-- /.form-group -->

                        <div class="form-group">
                            <label>সেকশন <span class="reqrd"> *</span></label>
                            <select class="form-control select2bs4" id="controller" name="controller" required>
                                <option value="">--- বাছাই করুণ ---</option>
                                <?php
                                $controller = config('constants.controller_list.list');
                                foreach ($controller as $id => $name){ ?>
                                <option
                                    value="{{ $id }}" {{ $id == $permissionData->controller ? 'selected="selected"' : '' }} >{{ $name }}</option>
                                <?php }
                                ?>
                            </select>

                            <span class="help-inline col-xs-12 col-sm-7">
                            @if ($errors->has('controller'))
                                    <span class="help-block middle">
                                    <strong>{{ $errors->first('controller') }}</strong>
                                </span>
                                @endif
                        </span>
                        </div>
                        <!-- /.form-group -->
                    {{--                    <div class="form-group">--}}
                    {{--                        <label>খতিয়ান</label>--}}
                    {{--                        <input type="text" class="form-control" placeholder="Enter ...">--}}
                    {{--                    </div>--}}
                    <!-- /.form-group -->
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>স্লাগ<span class="reqrd"></span></label>
                            <input type="text" id="name" name="slug" class="form-control" placeholder="স্লাগ"
                                   value="{{ $permissionData->slug }}" readonly>
                            <span class="help-inline col-xs-12 col-sm-7">
                            @if ($errors->has('slug'))
                                    <span class="help-block middle">
                                    <strong>{{ $errors->first('slug') }}</strong>
                                </span>
                                @endif
                        </span>
                        </div>
                        <!-- /.form-group -->
                    {{--                    <div class="form-group">--}}
                    {{--                        <label>খতিয়ান</label>--}}
                    {{--                        <input type="text" class="form-control" placeholder="Enter ...">--}}
                    {{--                    </div>--}}
                    <!-- /.form-group -->
                    </div>
                    <!-- /.col -->
                </div>
            </div>
            <!-- /.card-footer -->
            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>
@endsection

@section('custom_script')
    <script type="text/javascript">
        $(document).ready(function () {
        });

    </script>
@endsection