routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
//    return view('welcome');
    return view('auth.login');
});

Auth::routes();
Route::group(['middleware' => ['role:admin|user|super-admin|upazilla-admin']], function () {

    //*  Country Route Section */
    Route::get('country/list', 'CountryController@list')->name('country.list');   // index
    Route::get('country/add', 'CountryController@form')->name('country.form');    // create
    Route::post('country/store', 'CountryController@store')->name('country.store');   // store
    Route::get('country/{id}', 'CountryController@edit')->name('country.edit');   // edit
    Route::post('country/{id}', 'CountryController@update')->name('country.update');    // update
    Route::delete('country/{id}', 'CountryController@destroy')->name('country.delete');    // update

    //*  Division Route Section */
    Route::get('division/list', 'DivisionController@list')->name('division.list');   // index
    Route::get('division/add', 'DivisionController@form')->name('division.form');    // create
    Route::post('division/store', 'DivisionController@store')->name('division.store');   // store
    Route::post('division/divisionSelectAjaxList', 'DivisionController@divisionSelectAjaxList')->name('division.divisionSelectAjaxList');    // Ajax Division List
    Route::get('division/{id}', 'DivisionController@edit')->name('division.edit');   // edit
    Route::post('division/{id}', 'DivisionController@update')->name('division.update');    // update
    Route::delete('division/{id}', 'DivisionController@destroy')->name('division.delete');    // delete

    //*  District Route Section */
    Route::get('district/list', 'DistrictController@list')->name('district.list');   // index
    Route::get('district/add', 'DistrictController@form')->name('district.form');    // create
    Route::post('district/store', 'DistrictController@store')->name('district.store');   // store
    Route::post('district/districtSelectAjaxList', 'DistrictController@districtSelectAjaxList')->name('district.districtSelectAjaxList');    // Ajax District List
    Route::get('district/{id}', 'DistrictController@edit')->name('district.edit');   // edit
    Route::post('district/{id}', 'DistrictController@update')->name('district.update');    // update
    Route::delete('district/{id}', 'DistrictController@destroy')->name('district.delete');    // delete

    //*  Upazila-- Route Section */
    Route::get('upazila/list', 'UpazilaController@list')->name('upazila.list');   // index
    Route::get('upazila/add', 'UpazilaController@form')->name('upazila.form');    // create
    Route::post('upazila/store', 'UpazilaController@store')->name('upazila.store');   // store
    Route::post('upazila/upazilaSelectAjaxList', 'UpazilaController@upazilaSelectAjaxList')->name('upazila.upazilaSelectAjaxList');    // Ajax Upazila List
    Route::get('upazila/{id}', 'UpazilaController@edit')->name('upazila.edit');   // edit
    Route::post('upazila/{id}', 'UpazilaController@update')->name('upazila.update');    // update
    Route::delete('upazila/{id}', 'UpazilaController@destroy')->name('upazila.delete');    // delete

    //*  Union Route Section */
    Route::get('union/list', 'UnionController@list')->name('union.list');   // index
    Route::get('union/add', 'UnionController@form')->name('union.form');    // create
    Route::post('union/store', 'UnionController@Store')->name('union.store');   // store
    Route::post('union/unionSelectAjaxList', 'UnionController@unionSelectAjaxList')->name('union.unionSelectAjaxList');    // Ajax District List
    Route::get('union/{id}', 'UnionController@edit')->name('union.edit');   // edit
    Route::post('union/{id}', 'UnionController@update')->name('union.update');    // update
    Route::delete('union/{id}', 'UnionController@destroy')->name('union.delete');    // delete

    Route::get('/home', 'HomeController@index')->name('dashboard');

//    Route::get('/roles', 'PermissionController@Permission');

//    Route::get('/admin', function () {
//        return 'Welcome Admin';
//    });

//    bondobosto route
//    Route::get('/applicant', 'ApplicanrController@index')->name('applicant.list');

//    Land Route
    Route::post('/lands/getLandInfoById', 'LandController@getLandInfoById')->name('lands.getLandInfoById');
    Route::resource('/lands', 'LandController');

//    Applicant Route
    Route::resource('/applicants', 'ApplicantController');

//    Land Assign Route
    Route::resource('/assign_lands', 'AssignLandController');

//    Role Routs
    Route::Resource('/roles', 'RoleController');
    Route::get('/role-setting', 'RoleController@roleSetting')->name('roles.roleSetting');
    Route::post('/role-setting','RoleController@roleSetting')->name('roles.roleSetting');
    Route::post('/update-role-setting','RoleController@updateRoleSetting')->name('roles.updateRoleSetting');

//    Permission Routs
    Route::resource('/permissions','PermissionController');

//    User Route
//    Route::get("/users/datatable", 'UserController@datatable')->name("users.datatable"); // for Data Table Export
//    Route::get("/users/datatable/getData", 'UserController@getData')->name("users.getData"); // for datatable Export
    Route::get("/users/export", 'UserController@export')->name("users.export"); // for datatable Export
    Route::Resource('/users', 'UserController');
    Route::get("/change-password", 'UserController@changepass')->name("users.changepass"); // for pass change
    Route::post("/change-password", 'UserController@changepass')->name("users.changepass"); // for pass change
    Route::post("/reset-password", 'UserController@resetpass')->name("users.resetpass"); // for pass reset

//    Cache Clear Route
    Route::get('/clear-cache', function() {
        Artisan::call('cache:clear');
        Artisan::call('view:clear');
        Artisan::call('config:cache');
        return "Cache cleared";
    });
});


//Route::group(['middleware' => ['role:developer|manager|superadmin']], function () {
//});

/*
Verb            URI                         Action          Route Name
GET             /photos                     index           photos.index
GET             /photos/create              create          photos.create
POST            /photos                     store           photos.store
GET             /photos/{photo}             show            photos.show
GET             /photos/{photo}/edit        edit            photos.edit
PUT/PATCH       /photos/{photo}             update          photos.update
DELETE          /photos/{photo}             destroy         photos.destroy
*/

resources/views/includes/breadcrumb.blade.php
<ul class="breadcrumb">
    <li>
        <i class="ace-icon fa fa-home home-icon"></i>
        <a href="#">Home</a>
    </li>

    <li>
        <a href="#">Other Pages</a>
    </li>
    <li class="active">Blank Page</li>
</ul><!-- /.breadcrumb -->

<div class="nav-search" id="nav-search">
    <form class="form-search">
								<span class="input-icon">
									<input type="text" placeholder="Search ..." class="nav-search-input"
                                           id="nav-search-input" autocomplete="off"/>
									<i class="ace-icon fa fa-search nav-search-icon"></i>
								</span>
    </form>
</div><!-- /.nav-search -->

resources/views/includes/footer.blade.php
<!-- To the right -->
{{--<div class="float-right d-none d-sm-inline">--}}
{{--    Anything you want--}}
{{--</div>--}}
<!-- Default to the left -->
<strong>উদ্ভাবন,বাস্তবায়ন ও কারিগরী সহযোগিতায়: আকিব মোঃ সাদিকুল ইসলাম, প্রোগ্রামার, তথ্য ও যোগাযোগ প্রযুক্তি অধিদপ্তর, জেলা কার্যালয়, গোপালগঞ্জ</strong><br/>

resources/views/includes/head.blade.php
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- CSRF Token -->
<meta name="csrf-token" content="{{ csrf_token() }}">
<title>{{ config('app.name', 'Laravel') }}</title>

<!-- Scripts -->
{{--<script src="{{ asset('js/app.js') }}" defer></script>--}}

<!-- Google Font: Source Sans Pro -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
<!-- Font Awesome -->
<link rel="stylesheet" href="{{ asset('plugins/fontawesome-free/css/all.min.css') }} ">
<!-- Ionicons -->
{{--<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">--}}
<!-- Tempusdominus Bootstrap 4 -->
<link rel="stylesheet" href="{{ asset('plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css') }}">
<!-- iCheck -->
<link rel="stylesheet" href="{{ asset('plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
<!-- Bootstrap Color Picker -->
<link rel="stylesheet" href="{{ asset('plugins/bootstrap-colorpicker/css/bootstrap-colorpicker.min.css') }}">
<!-- Select2 -->
<link rel="stylesheet" href="{{ asset('plugins/select2/css/select2.min.css') }}">
<link rel="stylesheet" href="{{ asset('plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">
<!-- Bootstrap4 Duallistbox -->
<link rel="stylesheet" href="{{ asset('plugins/bootstrap4-duallistbox/bootstrap-duallistbox.min.css') }}">
<!-- BS Stepper -->
<link rel="stylesheet" href="{{ asset('plugins/bs-stepper/css/bs-stepper.min.css') }}">
<!-- dropzonejs -->
<link rel="stylesheet" href="{{ asset('plugins/dropzone/min/dropzone.min.css') }}">
<!-- JQVMap -->
<link rel="stylesheet" href="{{ asset('plugins/jqvmap/jqvmap.min.css') }}">
<!-- Theme style -->
<link rel="stylesheet" href="{{ asset('dist/css/adminlte.min.css') }}">
<!-- overlayScrollbars -->
<link rel="stylesheet" href="{{ asset('plugins/overlayScrollbars/css/OverlayScrollbars.min.css') }}">
<!-- Daterange picker -->
<link rel="stylesheet" href="{{ asset('plugins/daterangepicker/daterangepicker.css') }}">
<!-- summernote -->
<link rel="stylesheet" href="{{ asset('plugins/summernote/summernote-bs4.min.css') }}">
<!-- datatable -->
<link rel="stylesheet" href="{{ asset('plugins/datatables-buttons/css/buttons.bootstrap4.min.css') }}">

<!-- Custom SCC -->
<link rel="stylesheet" href="{{ asset('css/style.css') }}">

resources/views/includes/navbar.blade.php
<!-- Left navbar links -->
<ul class="navbar-nav">
    <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
        <a href="index3.html" class="nav-link">Home</a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
    </li>
</ul>

<!-- SEARCH FORM -->
<form class="form-inline ml-3">
    <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
            <button class="btn btn-navbar" type="submit">
                <i class="fas fa-search"></i>
            </button>
        </div>
    </div>
</form>

<!-- Right navbar links -->
<ul class="navbar-nav ml-auto">

    <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
            {{ Auth::user()->name }} <i class="right fas fa-angle-down"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
{{--            Change Password Change Option--}}
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ route('users.changepass') }}">
                {{ __('Change Password') }}
            </a>
            <div class="dropdown-divider"></div>

{{--            Logout Option--}}
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ route('logout') }}"
               onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                {{ __('Logout') }}
            </a>
            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                @csrf
            </form>

            <div class="dropdown-divider"></div>
        </div>
    </li>
</ul>

resources/views/includes/navbar_side.blade.php
<!-- Brand Logo -->
<a href="#" class="brand-link">
    {{--    <img src="dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">--}}
    <span class="brand-text font-weight-light">জমির বন্দবস্ত</span>
</a>

<!-- Sidebar -->
<div class="sidebar">
    <!-- Sidebar user panel (optional) -->
{{--    <div class="user-panel mt-3 pb-3 mb-3 d-flex">--}}
{{--        <div class="image">--}}
{{--            <img src="dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">--}}
{{--        </div>--}}
{{--        <div class="info">--}}
{{--            <a href="#" class="d-block">Alexander Pierce</a>--}}
{{--        </div>--}}
{{--    </div>--}}

<!-- Sidebar Menu -->
    <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column nav-child-indent" data-widget="treeview" role="menu"
            data-accordion="false">
            <!-- Add icons to the links using the .nav-icon class
                 with font-awesome or any other icon font library -->
            <li class="nav-item">
                <a href="{{ route('dashboard') }}" class="nav-link">
                    <i class="nav-icon fas fa-th"></i>
                    <p>ড্যাসবোর্ড
                    </p>
                </a>
            </li>
            <li class="nav-item">
                <a href="{{ route('lands.index') }}" class="nav-link">
                    <i class="nav-icon fas fa-th"></i>
                    <p>জমির তথ্য
                    </p>
                </a>
            </li>
            <li class="nav-item">
                <a href="{{ route('applicants.index') }}" class="nav-link">
                    <i class="nav-icon fas fa-th"></i>
                    <p>বন্দবস্ত গ্রহণকারীর তথ্য
                    </p>
                </a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link">
                    <i class="nav-icon fas fa-tachometer-alt"></i>
                    <p>
                        জমির বন্দোবস্ত
                        <i class="right fas fa-angle-left"></i>
                    </p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a href="{{ route('assign_lands.index') }}" class="nav-link active">
                            <i class="far fa-circle nav-icon"></i>
                            <p>বন্দোবস্তের ব্যবস্তা</p>
                        </a>
                    </li>
                    {{--                    <li class="nav-item">--}}
                    {{--                        <a href="#" class="nav-link">--}}
                    {{--                            <i class="far fa-circle nav-icon"></i>--}}
                    {{--                            <p>Inactive Page</p>--}}
                    {{--                        </a>--}}
                    {{--                    </li>--}}
                </ul>
            </li>
            <!--            --><?php
            //            if (check_view_role('super-admin')){
            //            ?>
            @role(array('super-admin'))
            <li class="nav-item">
                <a href="#" class="nav-link">
                    <i class="nav-icon fas fa-tachometer-alt"></i>
                    <p>
                        অনুমতি ব্যবস্তাপনা
                        <i class="right fas fa-angle-left"></i>
                    </p>
                </a>
                <ul class="nav nav-treeview">
{{--                    @can('create-task')--}}
                        <li class="nav-item">
                            <a href="{{ route('roles.index') }}" class="nav-link active">
                                <i class="far fa-circle nav-icon"></i>
                                <p>ইউজার রোল</p>
                            </a>
                        </li>
{{--                    @endcan--}}
                    <li class="nav-item">
                        <a href="{{ route('permissions.index') }}" class="nav-link active">
                            <i class="far fa-circle nav-icon"></i>
                            <p>ইউজার পারমিশন</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ route('roles.roleSetting') }}" class="nav-link active">
                            <i class="far fa-circle nav-icon"></i>
                            <p>রোল সেটিং</p>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link">
                    <i class="nav-icon fas fa-tachometer-alt"></i>
                    <p>
                        ইউজার ব্যবস্তাপনা
                        <i class="right fas fa-angle-left"></i>
                    </p>
                </a>
                <ul class="nav nav-treeview">
{{--                    @can('create-task')--}}
                        <li class="nav-item">
                            <a href="{{ route('users.index') }}" class="nav-link active">
                                <i class="far fa-circle nav-icon"></i>
                                <p>সকল ইউজার</p>
                            </a>
                        </li>
{{--                    @endcan--}}
                </ul>
            </li>
            @endrole
            <!--            --><?php //} ?>
            {{--            <li class="nav-item">--}}
            {{--                <a href="#" class="nav-link">--}}
            {{--                    <i class="nav-icon fas fa-th"></i>--}}
            {{--                    <p>--}}
            {{--                        Simple Link--}}
            {{--                        <span class="right badge badge-danger">New</span>--}}
            {{--                    </p>--}}
            {{--                </a>--}}
            {{--            </li>--}}
        </ul>
    </nav>
    <!-- /.sidebar-menu -->
</div>
<!-- /.sidebar -->

resources/views/includes/user_navbar_side.blade.php
<script type="text/javascript">
    try {
//        ace.settings.loadState('sidebar')
    } catch (e) {
    }
</script>


<ul class="nav nav-list">
    @if(Auth::user()->user_type == config('constants.userType.Owner'))
        <li class="active open">
            <a href="{{ route('client.dashboard') }}">
                <i class="menu-icon fa fa-tachometer"></i>
                <span class="menu-text"> Dashboard </span>
            </a>

            <b class="arrow"></b>
        </li>
{{--        <li class="">--}}
{{--            <a href="{{ route('client.clientList') }}">--}}
{{--                <i class="menu-icon fa fa-users"></i>--}}
{{--                <span class="menu-text"> Users </span>--}}
{{--            </a>--}}

{{--            <b class="arrow"></b>--}}
{{--        </li>--}}
{{--        <li class="">--}}
{{--            <a href="{{ route('trade.clientList') }}">--}}
{{--                <i class="menu-icon fa fa-flag"></i>--}}
{{--                <span class="menu-text"> Trades </span>--}}
{{--            </a>--}}

{{--            <b class="arrow"></b>--}}
{{--        </li>--}}
{{--        <li class="">--}}
{{--            <a href="{{ route('training.clientList') }}">--}}
{{--                <i class="menu-icon fa fa-graduation-cap"></i>--}}
{{--                <span class="menu-text"> Training </span>--}}
{{--            </a>--}}

{{--            <b class="arrow"></b>--}}
{{--        </li>--}}
        <li class="">
            <a href="{{ route('registration.clientList') }}">
                <i class="menu-icon fa fa-database"></i>
                <span class="menu-text">Registration </span>
            </a>

            <b class="arrow"></b>
        </li>
{{--        <li class="">--}}
{{--            <a href="{{ route('participant.clientList') }}">--}}
{{--                <i class="menu-icon fa fa-list"></i>--}}
{{--                <span class="menu-text"> Participant List </span>--}}
{{--            </a>--}}
{{--            <b class="arrow"></b>--}}
{{--        </li>--}}
{{--        <li class="">--}}
{{--            <a href="#" class="dropdown-toggle">--}}
{{--                <i class="menu-icon fa fa-line-chart"></i>--}}
{{--                <span class="menu-text"> Report </span>--}}
{{--                <b class="arrow fa fa-angle-down"></b>--}}
{{--            </a>--}}
{{--            <b class="arrow"></b>--}}
{{--            <ul class="submenu">--}}
{{--                <li class="">--}}
{{--                    <a href="#" class="dropdown-toggle">--}}
{{--                        <i class="menu-icon fa fa-pencil-square-o"></i>--}}
{{--                        <span class="menu-text"> Registration Report </span>--}}
{{--                        <b class="arrow fa fa-angle-down"></b>--}}
{{--                    </a>--}}
{{--                    <b class="arrow"></b>--}}
{{--                    <ul class="submenu">--}}
{{--                        <li class="">--}}
{{--                            <a href="{{ route('report.clientTrainingWiseRegistration') }}">--}}
{{--                                <i class="menu-icon fa fa-caret-right"></i>--}}
{{--                                Registration Report--}}
{{--                            </a>--}}

{{--                            <b class="arrow"></b>--}}
{{--                        </li>--}}
{{--                    </ul>--}}
{{--                </li>--}}
{{--                <li class="">--}}
{{--                    <a href="#" class="dropdown-toggle">--}}
{{--                        <i class="menu-icon fa fa-pencil-square-o"></i>--}}
{{--                        <span class="menu-text"> Training Report </span>--}}
{{--                        <b class="arrow fa fa-angle-down"></b>--}}
{{--                    </a>--}}
{{--                    <b class="arrow"></b>--}}
{{--                    <ul class="submenu">--}}
{{--                        <li class="">--}}
{{--                            <a href="{{ route('report.clientTrainingReport') }}">--}}
{{--                                <i class="menu-icon fa fa-caret-right"></i>--}}
{{--                                Training Report--}}
{{--                            </a>--}}
{{--                            <b class="arrow"></b>--}}
{{--                        </li>--}}
{{--                    </ul>--}}
{{--                </li>--}}
{{--                <li class="">--}}
{{--                    <a href="#" class="dropdown-toggle">--}}
{{--                        <i class="menu-icon fa fa-pencil-square-o"></i>--}}
{{--                        <span class="menu-text"> Participant Report </span>--}}
{{--                        <b class="arrow fa fa-angle-down"></b>--}}
{{--                    </a>--}}
{{--                    <b class="arrow"></b>--}}
{{--                    <ul class="submenu">--}}
{{--                        <li class="">--}}
{{--                            <a href="{{ route('report.clientParticipantReport') }}">--}}
{{--                                <i class="menu-icon fa fa-caret-right"></i>--}}
{{--                                Participant Report--}}
{{--                            </a>--}}
{{--                            <b class="arrow"></b>--}}
{{--                        </li>--}}
{{--                    </ul>--}}
{{--                </li>--}}
{{--            </ul>--}}
{{--        </li>--}}

    @elseif(Auth::user()->user_type == config('constants.userType.Tenant'))
        <li class="active open">
            <a href="{{ route('user.dashboard') }}">
                <i class="menu-icon fa fa-tachometer"></i>
                <span class="menu-text"> Dashboard </span>
            </a>

            <b class="arrow"></b>
        </li>

        <li class="">
            <a href="{{ route('registration.userList') }}">
                <i class="menu-icon fa fa-bullhorn"></i>
                <span class="menu-text">Trainee Registration </span>
            </a>

            <b class="arrow"></b>
        </li>
    @endif


    {{--<li class="">--}}
    {{--<a href="{{ route('client.adminList') }}">--}}
    {{--<i class="menu-icon fa fa-bullhorn"></i>--}}
    {{--<span class="menu-text"> Clients </span>--}}
    {{--</a>--}}

    {{--<b class="arrow"></b>--}}
    {{--</li>--}}

    {{--<li class="">--}}
    {{--<a href="#" class="dropdown-toggle">--}}
    {{--<i class="menu-icon fa fa-pencil-square-o"></i>--}}
    {{--<span class="menu-text"> Ledgers </span>--}}
    {{--<b class="arrow fa fa-angle-down"></b>--}}
    {{--</a>--}}
    {{--<b class="arrow"></b>--}}
    {{--<ul class="submenu">--}}
    {{--<li class="">--}}
    {{--<a href="{{ route('ledger.adminList') }}">--}}
    {{--<i class="menu-icon fa fa-caret-right"></i>--}}
    {{--Ledger Lists--}}
    {{--</a>--}}

    {{--<b class="arrow"></b>--}}
    {{--</li>--}}
    {{--</ul>--}}
    {{--</li>--}}

    {{--<li class="">--}}
    {{--<a href="#" class="dropdown-toggle">--}}
    {{--<i class="menu-icon fa fa-money"></i>--}}
    {{--<span class="menu-text"> Bills </span>--}}
    {{--<b class="arrow fa fa-angle-down"></b>--}}
    {{--</a>--}}
    {{--<b class="arrow"></b>--}}
    {{--<ul class="submenu">--}}
    {{--<li class="">--}}
    {{--<a href="{{ route('bill.adminList') }}">--}}
    {{--<i class="menu-icon fa fa-caret-right"></i>--}}
    {{--Bill Lists--}}
    {{--</a>--}}

    {{--<b class="arrow"></b>--}}
    {{--</li>--}}
    {{--</ul>--}}
    {{--</li>--}}

    {{--<li class="">--}}
    {{--<a href="#" class="dropdown-toggle">--}}
    {{--<i class="menu-icon fa fa-credit-card" aria-hidden="true"></i>--}}
    {{--<span class="menu-text"> Payment </span>--}}
    {{--<b class="arrow fa fa-angle-down"></b>--}}
    {{--</a>--}}
    {{--<b class="arrow"></b>--}}
    {{--<ul class="submenu">--}}
    {{--<li class="">--}}
    {{--<a href="{{ route('payment.adminList') }}">--}}
    {{--<i class="menu-icon fa fa-caret-right"></i>--}}
    {{--Payment Lists--}}
    {{--</a>--}}

    {{--<b class="arrow"></b>--}}
    {{--</li>--}}
    {{--</ul>--}}
    {{--</li>--}}

</ul><!-- /.nav-list -->

<div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse">
    <i id="sidebar-toggle-icon" class="ace-icon fa fa-angle-double-left ace-save-state"
       data-icon1="ace-icon fa fa-angle-double-left" data-icon2="ace-icon fa fa-angle-double-right"></i>
</div>