routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
//    return view('welcome');
    return view('auth.login');
});

Auth::routes();
Route::group(['middleware' => ['role:admin|user|super-admin|upazilla-admin']], function () {

    //*  Country Route Section */
    Route::get('country/list', 'CountryController@list')->name('country.list');   // index
    Route::get('country/add', 'CountryController@form')->name('country.form');    // create
    Route::post('country/store', 'CountryController@store')->name('country.store');   // store
    Route::get('country/{id}', 'CountryController@edit')->name('country.edit');   // edit
    Route::post('country/{id}', 'CountryController@update')->name('country.update');    // update
    Route::delete('country/{id}', 'CountryController@destroy')->name('country.delete');    // update

    //*  Division Route Section */
    Route::get('division/list', 'DivisionController@list')->name('division.list');   // index
    Route::get('division/add', 'DivisionController@form')->name('division.form');    // create
    Route::post('division/store', 'DivisionController@store')->name('division.store');   // store
    Route::post('division/divisionSelectAjaxList', 'DivisionController@divisionSelectAjaxList')->name('division.divisionSelectAjaxList');    // Ajax Division List
    Route::get('division/{id}', 'DivisionController@edit')->name('division.edit');   // edit
    Route::post('division/{id}', 'DivisionController@update')->name('division.update');    // update
    Route::delete('division/{id}', 'DivisionController@destroy')->name('division.delete');    // delete

    //*  District Route Section */
    Route::get('district/list', 'DistrictController@list')->name('district.list');   // index
    Route::get('district/add', 'DistrictController@form')->name('district.form');    // create
    Route::post('district/store', 'DistrictController@store')->name('district.store');   // store
    Route::post('district/districtSelectAjaxList', 'DistrictController@districtSelectAjaxList')->name('district.districtSelectAjaxList');    // Ajax District List
    Route::get('district/{id}', 'DistrictController@edit')->name('district.edit');   // edit
    Route::post('district/{id}', 'DistrictController@update')->name('district.update');    // update
    Route::delete('district/{id}', 'DistrictController@destroy')->name('district.delete');    // delete

    //*  Upazila-- Route Section */
    Route::get('upazila/list', 'UpazilaController@list')->name('upazila.list');   // index
    Route::get('upazila/add', 'UpazilaController@form')->name('upazila.form');    // create
    Route::post('upazila/store', 'UpazilaController@store')->name('upazila.store');   // store
    Route::post('upazila/upazilaSelectAjaxList', 'UpazilaController@upazilaSelectAjaxList')->name('upazila.upazilaSelectAjaxList');    // Ajax Upazila List
    Route::get('upazila/{id}', 'UpazilaController@edit')->name('upazila.edit');   // edit
    Route::post('upazila/{id}', 'UpazilaController@update')->name('upazila.update');    // update
    Route::delete('upazila/{id}', 'UpazilaController@destroy')->name('upazila.delete');    // delete

    //*  Union Route Section */
    Route::get('union/list', 'UnionController@list')->name('union.list');   // index
    Route::get('union/add', 'UnionController@form')->name('union.form');    // create
    Route::post('union/store', 'UnionController@Store')->name('union.store');   // store
    Route::post('union/unionSelectAjaxList', 'UnionController@unionSelectAjaxList')->name('union.unionSelectAjaxList');    // Ajax District List
    Route::get('union/{id}', 'UnionController@edit')->name('union.edit');   // edit
    Route::post('union/{id}', 'UnionController@update')->name('union.update');    // update
    Route::delete('union/{id}', 'UnionController@destroy')->name('union.delete');    // delete

    Route::get('/home', 'HomeController@index')->name('dashboard');

//    Route::get('/roles', 'PermissionController@Permission');

//    Route::get('/admin', function () {
//        return 'Welcome Admin';
//    });

//    bondobosto route
//    Route::get('/applicant', 'ApplicanrController@index')->name('applicant.list');

//    Land Route
    Route::post('/lands/getLandInfoById', 'LandController@getLandInfoById')->name('lands.getLandInfoById');
    Route::resource('/lands', 'LandController');

//    Applicant Route
    Route::resource('/applicants', 'ApplicantController');

//    Land Assign Route
    Route::resource('/assign_lands', 'AssignLandController');

//    Role Routs
    Route::Resource('/roles', 'RoleController');
    Route::get('/role-setting', 'RoleController@roleSetting')->name('roles.roleSetting');
    Route::post('/role-setting','RoleController@roleSetting')->name('roles.roleSetting');
    Route::post('/update-role-setting','RoleController@updateRoleSetting')->name('roles.updateRoleSetting');

//    Permission Routs
    Route::resource('/permissions','PermissionController');

//    User Route
//    Route::get("/users/datatable", 'UserController@datatable')->name("users.datatable"); // for Data Table Export
//    Route::get("/users/datatable/getData", 'UserController@getData')->name("users.getData"); // for datatable Export
    Route::get("/users/export", 'UserController@export')->name("users.export"); // for datatable Export
    Route::Resource('/users', 'UserController');
    Route::get("/change-password", 'UserController@changepass')->name("users.changepass"); // for pass change
    Route::post("/change-password", 'UserController@changepass')->name("users.changepass"); // for pass change
    Route::post("/reset-password", 'UserController@resetpass')->name("users.resetpass"); // for pass reset

//    Cache Clear Route
    Route::get('/clear-cache', function() {
        Artisan::call('cache:clear');
        Artisan::call('view:clear');
        Artisan::call('config:cache');
        return "Cache cleared";
    });
});


//Route::group(['middleware' => ['role:developer|manager|superadmin']], function () {
//});

/*
Verb            URI                         Action          Route Name
GET             /photos                     index           photos.index
GET             /photos/create              create          photos.create
POST            /photos                     store           photos.store
GET             /photos/{photo}             show            photos.show
GET             /photos/{photo}/edit        edit            photos.edit
PUT/PATCH       /photos/{photo}             update          photos.update
DELETE          /photos/{photo}             destroy         photos.destroy
*/

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    public function permissions() {

        return $this->belongsToMany(Permission::class,'roles_permissions');
            
     }
     
     public function users() {
     
        return $this->belongsToMany(User::class,'users_roles');
            
     }
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Permission;
use Illuminate\Http\Request;
use DataTables;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use App\Role;
use Auth;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $page_title = 'সকল রোল ';
        $data = Role::orderBy('id', 'asc')->get();
//        $slug = Str::slug("This is it");
//        dd($slug);
        if ($request->ajax()) {
            return DataTables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function ($row) {
                    $action = '<a class="btn btn-success" id="edit-role" href= ' . route('roles.edit', $row->id) . '>Edit </a>
<meta name="csrf-token" content="{{ csrf_token() }}">
<a id=' . $row->id . ' href=' . route('roles.destroy', $row->id) . ' class="btn btn-danger delete-role">Delete</a>';
                    return $action;
                })
                ->rawColumns(['action'])
                ->make(true);
//            <a class="btn btn-info" id="show-user" href=' . route('lands.show', $row->id) . '>Show</a>
        }

        return view('roles.index', compact('page_title'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $page_title = 'ইউজার রোল তৈরী';
        return view('roles.create', compact('page_title'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $formData = $request->all();

        DB::beginTransaction();
        try {
            $role_name = $formData['name'];
            $slug = Str::slug($role_name);
            $request->request->add(['slug' => $slug]);

            $data = $this->validate($request, [
                'name' => 'required',
            ], [
                'name.required' => 'অনুগ্রহ করে ইউজার রোল প্রদাল করুন',
            ]);

            $dev_role = new Role();
            $dev_role->slug = $slug;
            $dev_role->name = $role_name;
            $dev_role->save();

//            $lastInsertedId = $landModel->saveData($request);

            DB::commit();
            return redirect('/roles')->with('success', 'নতুন ইউজার রোল যুক্ত হয়েছে।');
        } catch (\Exception $exception) {
            DB::rollback();
            return redirect('/roles/create')->with('error', $exception->getMessage());
//			$request->session()->flash('errors', $exception->getMessage());
            //$request->session()->flash('errors', $exception);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param int $id `
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $page_title = 'ইউজার রোল সংশোধন';
//        $countryData = Country::all();
        $roleModel = new Role();
        try {
            $roleData = $roleModel->where('roles.id', $id)
                ->firstOrFail();

            return view('roles.edit', compact('page_title', 'roleData', 'id'));
        } catch (\Exception $exception) {
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $formData = $request->all();
        DB::beginTransaction();
        try {
            $request->request->add(['id' => $id]);
            $data = $this->validate($request, [
                'name' => 'required',
            ], [
                'name.required' => 'অনুগ্রহ করে ইউজার রোল প্রদাল করুন',
            ]);

            $role_name = $formData['name'];

            $data = Role::find($id);
            $data->name = $role_name;

            $data->save();
//            dd($request);
            DB::commit();

//            return redirect()->back()->with('success', 'data updated');
            return redirect('/roles')->with('success', 'তথ্য সফলভাবে সংশোধন হয়েছে।');
        } catch (\Exception $exception) {
            DB::rollback();
            dd($exception);
            return redirect("/roles/$id/edit")->with('error', 'তথ্য সংশোধন সম্ভব হয় নি। ' . $exception->getMessage());
//			$request->session()->flash('errors', $exception->getMessage());
            //$request->session()->flash('errors', $exception);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        DB::beginTransaction();
        try {
            if (!empty($id)) {
                Role::destroy($id);
                DB::commit();
                $request->session()->flash('success', 'তথ্য সফলভাবে নুছে ফেলা হয়েছে...');
                return response()->json(['status' => 'success']);
            } else {
                DB::rollback();
                $request->session()->flash('errors', 'কোন তথ্য পাওয়া জায় নি...');
                return response()->json(['status' => 'error']);
            }
        } catch (\Exception $exception) {
            DB::rollback();
            $request->session()->flash('errors', 'তথ্য সফলভাবে মুছা সম্ভব হয় নি...');
            return response()->json(['status' => 'error']);
        }
    }

    public function roleSetting()
    {
        $page_title = 'রোল সেটিং';
        $roleListArr = Role::orderby('id', 'asc')->get();
        $permissionListArr = Permission::orderby('id', 'asc')->get();

        $results = DB::select('select roles_permissions.*, permissions.controller  from roles_permissions left join permissions on(roles_permissions.permission_id = permissions.id) WHERE controller is not NULL');
//            ->leftJoin('permissions', 'permissions.id', 'roles_permissions.permission_id')->get();
        $rolPermArray = [];
//        dd($results);
        foreach ($results as $key =>$val){
            $controller = $val->controller;
            $rId = $val->role_id;
            $permId = $val->permission_id;

//            if(!isset($rolPermArray[$controller]))
//            $rolPermArray[$controller] = [];

            if(!isset($rolPermArray[$rId]))
                $rolPermArray[$rId] = [];

            if(!isset($rolPermArray[$rId][$permId]))
                $rolPermArray[$rId][$permId] = $permId;
        }

//        dd($rolPermArray);
//        pr($rolPermArray);

//        dd($permissionListArr);
        if (isset($_POST['role_arr'])) {
//            dd($_POST);
        }
        return view('roles.role_setting', compact('page_title', 'roleListArr', 'permissionListArr','rolPermArray'));
    }

    public function updateRoleSetting(Request $request)
    {
        DB::beginTransaction();
        try {
            $id = $request->post('id');
            $status = $request->post('status');
            $explodData = explode('_', $id);
            if ($status === 'true') {
                echo "true";
                DB::insert('insert into roles_permissions (role_id, permission_id) values (?, ?)', [$explodData[0], $explodData[1]]);
                DB::commit();
                $resData = [
                    'status' => 'success',
                ];

                return json_encode($resData);
            } else {
                echo "false";
                $deleted = DB::delete('delete from roles_permissions where role_id = ? and permission_id = ?', [$explodData[0], $explodData[1]]);
                DB::commit();
                $resData = [
                    'status' => 'success',
                ];

                return json_encode($resData);
            }
//            pr($explodData);
//            dd($request->post());
        } catch (\Exception $exception) {
            DB::rollback();
            $resData = [
                'status' => 'error',
                'msg' => $exception
            ];

            return json_encode($resData);
        }


    }
}

resources/views/roles/create.blade.php
@extends('layouts.app')

@section('pagetitle')
    <h1 class="m-0">{{ $page_title }}</h1>
@endsection

@section('breadcrumb')
    <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="#">Home</a></li>
        <li class="breadcrumb-item active">Starter Page</li>
    </ol>
@endsection

@section('content')
    <form class="form-horizontal" role="form" action="{{ route('roles.store') }}" method="POST"
          enctype="multipart/form-data" id="reg_form">
        {{ csrf_field() }}


        <div class="card  card-primary">
            <div class="card-header">
                <h3 class="card-title">ইউজার রোল</h3>

                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    {{--                <button type="button" class="btn btn-tool" data-card-widget="remove">--}}
                    {{--                    <i class="fas fa-times"></i>--}}
                    {{--                </button>--}}
                </div>
            </div>
            <!-- /.card-header -->
            <!-- /.card-body -->
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>ইউজার রোল নাম<span class="reqrd"> *</span></label>
                            <input type="text" id="name" name="name" class="form-control" placeholder="ইউজার রোল নাম"
                                   required>
                            <span class="help-inline col-xs-12 col-sm-7">
                            @if ($errors->has('name'))
                                    <span class="help-block middle">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                                @endif
                        </span>
                        </div>
                        <!-- /.form-group -->
                    {{--                    <div class="form-group">--}}
                    {{--                        <label>খতিয়ান</label>--}}
                    {{--                        <input type="text" class="form-control" placeholder="Enter ...">--}}
                    {{--                    </div>--}}
                    <!-- /.form-group -->
                    </div>
                    <!-- /.col -->
                </div>
            </div>
            <!-- /.card-footer -->
            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>
@endsection

@section('custom_script')
    <script type="text/javascript">
        $(document).ready(function () {
        });
    </script>
@endsection

resources/views/roles/edit.blade.php
@extends('layouts.app')

@section('pagetitle')
    <h1 class="m-0">{{ $page_title }}</h1>
@endsection

@section('breadcrumb')
    <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="#">Home</a></li>
        <li class="breadcrumb-item active">Starter Page</li>
    </ol>
@endsection

@section('content')
    <form class="form-horizontal" role="form" action="{{ route('roles.update', $id) }}" method="POST"
          enctype="multipart/form-data" id="reg_form">
        <input type="hidden" name="_method" value="PUT">
        {{ csrf_field() }}


        <div class="card  card-primary">
            <div class="card-header">
                <h3 class="card-title">ইউজার রোল</h3>

                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    {{--                <button type="button" class="btn btn-tool" data-card-widget="remove">--}}
                    {{--                    <i class="fas fa-times"></i>--}}
                    {{--                </button>--}}
                </div>
            </div>
            <!-- /.card-header -->
            <!-- /.card-body -->
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>ইউজার রোল নাম<span class="reqrd"> *</span></label>
                            <input type="text" id="name" name="name" class="form-control" placeholder="কইউজার রোল নাম"
                                   required value="{{ $roleData->name }}">
                            <span class="help-inline col-xs-12 col-sm-7">
                            @if ($errors->has('name'))
                                    <span class="help-block middle">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                                @endif
                        </span>
                        </div>
                        <!-- /.form-group -->
                    {{--                    <div class="form-group">--}}
                    {{--                        <label>খতিয়ান</label>--}}
                    {{--                        <input type="text" class="form-control" placeholder="Enter ...">--}}
                    {{--                    </div>--}}
                    <!-- /.form-group -->
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>স্লাগ<span class="reqrd"></span></label>
                            <input type="text" id="name" name="slug" class="form-control" placeholder="স্লাগ"
                                   value="{{ $roleData->slug }}" readonly>
                            <span class="help-inline col-xs-12 col-sm-7">
                            @if ($errors->has('slug'))
                                    <span class="help-block middle">
                                    <strong>{{ $errors->first('slug') }}</strong>
                                </span>
                                @endif
                        </span>
                        </div>
                        <!-- /.form-group -->
                    {{--                    <div class="form-group">--}}
                    {{--                        <label>খতিয়ান</label>--}}
                    {{--                        <input type="text" class="form-control" placeholder="Enter ...">--}}
                    {{--                    </div>--}}
                    <!-- /.form-group -->
                    </div>
                    <!-- /.col -->
                </div>
            </div>
            <!-- /.card-footer -->
            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>
@endsection

@section('custom_script')
    <script type="text/javascript">
        $(document).ready(function () {
        });

    </script>
@endsection

resources/views/roles/role_setting.blade.php
@extends('layouts.app')


@section('content')

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-12">
                    <!-- jquery validation -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">{!! $page_title !!}</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
{{--                        <form class="form-horizontal" role="form" action="{{ route('roles.store') }}" method="POST"--}}
{{--                              enctype="multipart/form-data" id="reg_form">--}}
{{--                            {{ csrf_field() }}--}}
                        <form method="POST" action="{{ route('roles.roleSetting') }}" id="quickForm">
                            @csrf
                            <div class="card-body">
                                <table id="role_lists" class="table table-bordered table-striped">
                                    <thead>
                                    <tr>
                                        @if(count($roleListArr) > 0)
                                            @foreach($roleListArr as $role)
                                                <th>{!! $role->name !!}</th>
                                            @endforeach
                                        @endif
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @if(count($permissionListArr) > 0)
                                        @foreach($permissionListArr as $s_page)
{{--                                            <tr>--}}
{{--                                                @foreach($roleListArr as $role)--}}
{{--                                                    <td><input--}}
{{--                                                            @if(isset($role_arr[$role->slug][$s_page->name]) && $role_arr[$role->slug][$s_page->name]=='on') checked--}}
{{--                                                            @endif type="checkbox"--}}
{{--                                                            name=role_arr[{!! $role->slug !!}][{!! $s_page->name !!}]> {!! $s_page->name !!}--}}
{{--                                                    </td>--}}
{{--                                                @endforeach--}}
{{--                                            </tr>--}}
                                            <tr>
                                                <?php
//                                                dd($roleListArr);
                                                ?>
                                                @foreach($roleListArr as $role)

                                                    <td>
{{--                                                        <input--}}
{{--                                                            @if(isset($role_arr[$role->id][$s_page->id]) && $role_arr[$role->id][$s_page->id]=='on') checked--}}
{{--                                                            @endif type="checkbox" id="{!! $role->id !!}_{!! $s_page->id !!}" class="roll_permission"--}}
{{--                                                            name=role_arr[{!! $role->id !!}][{!! $s_page->id !!}]> {!! $s_page->name !!}--}}
                                                        <input
                                                            @if(isset($rolPermArray[$role->id][$s_page->id]) && $rolPermArray[$role->id][$s_page->id]== $s_page->id) checked
                                                            @endif type="checkbox" id="{!! $role->id !!}_{!! $s_page->id !!}" class="roll_permission"
                                                            name=role_arr[{!! $role->id !!}][{!! $s_page->id !!}]> {!! $s_page->name !!}
                                                    </td>
                                                @endforeach
                                            </tr>
                                        @endforeach
                                    @endif
                                    </tbody>

                                    <tfoot>
                                    </tfoot>
                                </table>
                                <br/>
                                <input type="submit" class="btn btn-primary float_right" value="Submit">
                            </div>

                        </form>
                    </div>
                    <!-- /.card -->
                </div>
                <!--/.col (left) -->
                <!-- right column -->
                <div class="col-md-6">

                </div>
                <!--/.col (right) -->
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->




@endsection

@section('custom_script')
    <script type="text/javascript">
        $(document).ready(function () {
        });

        $('.roll_permission').change(function (){
            // alert($(this).attr('id'));
            let flag = false;
            if ($(this).prop('checked')) {
                flag = true;
                alert('Checked');
            }else{
                flag = false;
                alert('Not Checked');
            }
            let url = "{{ route('roles.updateRoleSetting') }}";
            let ids = $(this).attr('id');
            let status = flag;
            $.ajax({
                type: 'POST',
                url: url,
                dataType: 'json',
                headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                data: {id: ids, status: status, "_token": "{{ csrf_token() }}"},

                success: function (data) {
                    if (data.status == 'success') {
                        window.location.reload();
                    } else if (data.status == 'error') {
                        console.log(data.msg);
                    }
//                    data.request->session()->flash('status', 'Task was successful!');
//                    setInterval(function() {
//                    }, 5900);
                },
                error: function (data) {
                }
            });
        });
    </script>

@endsection